# Environment parameters
random_seed: 2
state_size: 7
action_size: 2
episode_duration: 30
first_area: 'on'
first_area_step_size: 0.01
second_area: 'off'
second_area_step_size: 0.0

# Training parameters
batch_size: 256
replay_mem_size: 1000000
discount_rate: 0.99
n_episodes: 10000
log_every: 100
noise_decay_value: 0.99

# Network parameters
critic_learning_rate: 0.0001
actor_learning_rate: 0.0001
hidden_units: !!python/tuple [400, 300]
gate: F.relu
gamma: 0.99
weight_decay: 0
tau: 0.001